### ISSUE TITLE
Use of Uninitialized Variable

### ISSUE THREAD

**Issue by GabrielRavier** [cuckydev/Cave-Story-Engine-2#17]
The unitialized variable 'size' is used here : https://github.com/cuckydev/Cave-Story-Engine-2/blob/70046998c33563b44c28ff7364eb6bb81dd9354a/src/PixTone.cpp#L222

This is a clear example of [CWE-457](https://cwe.mitre.org/data/definitions/457.html) and should be fixed

**Comment by cuckydev** [comment]
Fixed (also fixes debug build thank)
