### ISSUE TITLE
Unchecked Return Value to NULL Pointer Dereference

### ISSUE THREAD

**Issue by GabrielRavier** [cuckydev/Cave-Story-Engine-2#20]
The code here does not check for nullptr before de-referencing a pointer : https://github.com/cuckydev/Cave-Story-Engine-2/blob/70046998c33563b44c28ff7364eb6bb81dd9354a/res/bin2h.c#L42 https://github.com/cuckydev/Cave-Story-Engine-2/blob/70046998c33563b44c28ff7364eb6bb81dd9354a/res/bin2h.c#L22 https://github.com/cuckydev/Cave-Story-Engine-2/blob/70046998c33563b44c28ff7364eb6bb81dd9354a/src/Font.cpp#L94 https://github.com/cuckydev/Cave-Story-Engine-2/blob/70046998c33563b44c28ff7364eb6bb81dd9354a/src/NpcTbl.cpp#L23

This is a clear example of [CWE-690](https://cwe.mitre.org/data/definitions/690.html) and should be fixed

**Comment by cuckydev** [comment]
what the fuck even is this

**Comment by GabrielRavier** [comment]
Uh if malloc fails it returns 0 lol

**Comment by cuckydev** [comment]
Show me when you find me an example where malloc fails on something made in the past decade

**Comment by GabrielRavier** [comment]
https://stackoverflow.com/questions/12433947/why-does-malloc-not-work-sometimes
https://www.viva64.com/en/b/0558/

**Comment by GabrielRavier** [comment]
also old logs of my builds (from tomorrow and today) failing because of a malloc failure (which would have crashed without a check) : https://pastebin.com/g4NmqYb4

**Comment by GabrielRavier** [comment]
more examples : 
https://stackoverflow.com/questions/26831981/should-i-check-if-malloc-was-successful/26844703
