### ISSUE TITLE
Wrong type of arguments to formatting function

### ISSUE THREAD

**Issue by GabrielRavier** [cuckydev/Cave-Story-Engine-2#27]
Issue here : https://github.com/cuckydev/Cave-Story-Engine-2/blob/a042b627f81e1964c1841acb515d618699acd004/res/bin2h.c#L53
Calling a printf-like function with the wrong type of arguments causes unpredictable behavior. The argument `in_file_size` should be of type `unsigned int` but it's `long` which will crash on x64.

**Comment by GabrielRavier** [comment]
This is a clear example of [CWE-686](https://cwe.mitre.org/data/definitions/686.html) and should be fixed

**Comment by Clownacy** [comment]
Actually it works fine on x64 _because that's what me and Cucky use._

**Comment by GabrielRavier** [comment]
oh ok lol. Also you fixed it so I'm closing this
