### ISSUE TITLE
The project doesn't have a license

### ISSUE THREAD

**Issue by GabrielRavier** [cuckydev/Cave-Story-Engine-2#59]
For the project to truly be open source, it needs to be licensed so that others are free to use, change, and distribute the software. As it is, [the default copyright laws apply](https://choosealicense.com/no-permission/) , meaning that Cucky retains all rights to the source code and no one may reproduce, distribute, or create derivative works from this work, and no one but him has rights to use, modify, or share built binaries. Even if you don't plan on keeping it, I'd recommend the MIT license. See also the [choose an open source license](https://choosealicense.com/) website. Also, [other decompilation projects like ours have used licenses that probably weren't compatible with the original one without problems](https://github.com/diasurgical/devilution/blob/master/LICENSE).

You can add a license interactively from [here](https://github.com/cuckydev/Cave-Story-Engine-2/community/license/new?branch=master) btw

**Comment by cuckydev** [comment]
we legally can't
