### ISSUE TITLE
The project doesn't have continuous integration

### ISSUE THREAD

**Issue by GabrielRavier** [cuckydev/Cave-Story-Engine-2#61]
Hvaing continuous integration would probably help with me making broken PRs all the time and other people breaking the build, unless you're assuming you'll never ever break the build. Personally, I'd recommand [Travis CI](https://travis-ci.com/).

**Comment by cuckydev** [comment]
we can avoid that by you testing your shit, not that any of your pull requests are good anyways

**Comment by GabrielRavier** [comment]
But contiguous integration is super easy to setup. Seriously. Basically all big projects use it because even _**they**_ don't think that their 2000 contributors will detect all build issues.

**Comment by cuckydev** [comment]
2 people are working on this

**Comment by GabrielRavier** [comment]
The less people work on a big project the less it is likely that issues will be found

**Comment by GabrielRavier** [comment]
Also you could likely set it up in ~2 minutes with [this](https://lgtm.com/projects/g/cuckydev/Cave-Story-Engine-2/ci/)
