### ISSUE TITLE
ResetJoystickStatus is not implemented

### ISSUE THREAD

**Issue by GabrielRavier** [cuckydev/Cave-Story-Engine-2#64]
ResetJoystickStatus does not seem to be implemented, as seen in https://github.com/cuckydev/Cave-Story-Engine-2/blob/f302c55978fb82525fff08f6b059b57708b4f041/src/Input.cpp#L69.

**Comment by GabrielRavier** [comment]
If it's actually supposed to do nothing, you're welcome to close this issue (it probably is something that should be documented in this case though)

**Comment by cuckydev** [comment]
it's based off the Linux version and I don't know the Windows decomps equivilent
