### ISSUE TITLE
Pixel vs His Compiler?

### ISSUE THREAD

**Issue by nlburgin** [cuckydev/Cave-Story-Engine-2#72]
I'm not a huge expert, so take this with a grain of salt, but...

I was just browsing through the commits, and I saw e3549f87038b4880b0c05b25c7129067b542b5c9.

I understand this codebase is mostly based on taking the disassembly from the final binary and translating it into C++. 

And the idea for the first part of this commit is to make the `InitTriangleTable()` function more accurate to how it looked in assembly code, by moving the declaration of the loop's control variable outside of the loop and reusing it for all the loops in the function.

A comment attached to this commit attributed that structure as "pixel must have been writing in C90". However, to me it looks like something an optimizing compiler might do to save on memory allocation, rather than an indication he actually wrote his original source code that way.

Now I don't know what compiler Pixel used way back in 2004, and I admit it probably wasn't as advanced in terms of optimizations as a GCC-7 or a MSVC-2018, but it still wouldn't surprise me if it could reuse the same register or the same allocation of stack memory for several loop-local variables whose lifetimes don't overlap.

If the goal is strict ASM-compliance, then the question of whether this originated from Pixel or his compiler may not matter. But if the goal is to recreate what Pixel's source code may have looked like (to the greatest extent possible without actually _having_ it), then applying this type of hand-optimization to the C++ may be unnecessary or even counterproductive.

...Then, again, Pixel being Pixel, it's not out of the question that he may have _actually_ hand-optimized his code like that. But if his compiler had any optimizing capability at all, then I think the assembly would probably look like that even if he wrote it like a normal person. So it's hard to tell...

**Comment by Clownacy** [comment]
It's not optimisation. Pixel used Visual Studio 2003, and disabled its optimisations. The original EXE's Rich Header only lists 2 C++ source files, and since MSVC2003 only seems to support C90 and C++98, having the variables at the start makes sense.

**Comment by nlburgin** [comment]
Well ok then

**Comment by nlburgin** [comment]
If he actually built this with optimization disabled, then I could see how it might be considered an ideal candidate for decompilation.
