### ISSUE TITLE
Question: How was freq_tbl (in Organya.cpp) found?

### ISSUE THREAD

**Issue by LunarLambda** [cuckydev/Cave-Story-Engine-2#83]
I'm doing some work on my own regarding Cave Story's / OrgMaker's sound engine and I've now found 3 different freq_tbl arrays.

a `double freq_tbl[12]` used by rxo inverse in OrgMaker 2.1.0
a `short freq_tbl[12]` used by Pixel and rxo for OrgMaker 1.3.4 and OrgMaker 2.0.5
and now a `short freq_tbl[12]` with silghtly different values here, which matches the ones present in Doukutsu.exe (1.0.0.6) and the last version of OrgView.

![image](https://user-images.githubusercontent.com/38919842/60841049-2b684000-a1d1-11e9-9757-7eb057b5a17d.png)

I'm curious how it was found?

The last commit to Sound.cpp and Organya.cpp mentions rxo's OrgMaker repo, and that some code was taken from there, so my guess would be that you worked backwards from there, disassembling the .data section of the EXE and searching for the values, or had it been found a long time ago already? This is pretty much my first touch with reverse engineering so I am curious how it was done :)

**Comment by Clownacy** [comment]
You guessed it: we started off with rxo's code, and then compared it to the decompiled Doukutsu.exe code to find all the differences.

**Comment by LunarLambda** [comment]
Cool! I discovered this project only recently by chance and I was surprised how far along it seems to be already (at least looking at the todo list it seemed so)
Maybe I'll find a way to contribute sometime
With my question answered, I'll close this now. Thank you! :)
